# Generated by Django 4.1.4 on 2023-08-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaDeNoticias",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SiteDeNoticias",
            fields=[
                ("id_site", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("task", models.CharField(max_length=25)),
                ("success", models.BooleanField(default=True)),
                ("response", models.JSONField(null=True)),
            ],
            options={
                "db_table": "tracker",
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("id_noticia", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_publicacao", models.DateTimeField()),
                ("url", models.URLField()),
                ("relevante", models.BooleanField()),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eagle.categoriadenoticias",
                    ),
                ),
                (
                    "id_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eagle.sitedenoticias",
                    ),
                ),
            ],
        ),
    ]
